version: '3.9'

services:
  front:
    build:
      dockerfile: Dockerfile-front
      context: .

  postgres_db:
    container_name: star_burger_db
    image: postgres:15.3
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    depends_on:
      - front

  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: star_burger:latest
    container_name: star_burger
    depends_on:
      - postgres_db
    volumes:
      - static_volume:/star-burger/static
      - media_volume:/star-burger/media
    env_file:
      - .env
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn star_burger.wsgi:application - 127.0.0.1:8081 -w 4"
    ports:
      - "8080:8081"

  nginx:
    container_name: star_burger_nginx
    image: nginx:1.18.0
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/star-burger/static
      - media_volume:/star-burger/media
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/nginx/proxy_params:/etc/nginx/proxy_params
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"

volumes:
  pg_data:
  static_volume:
  media_volume:
