# Generated by Django 3.2.15 on 2023-08-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geocodedata',
            options={'verbose_name': 'Данные геолокации', 'verbose_name_plural': 'Данные геолокации'},
        ),
        migrations.AlterUniqueTogether(
            name='geocodedata',
            unique_together={('address',)},
        ),
    ]
