# Generated by Django 3.2.15 on 2023-08-16 21:34

import django.core.validators
from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderelements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='contact_phone',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='orderelements',
            old_name='product_number',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='orderelements',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[foodcartapp.models.validate_price, django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
