# Generated by Django 3.2.15 on 2023-08-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230816_2134'),
    ]

    def update_price_from_product(apps, schema_editor):
        OrderElements = apps.get_model('foodcartapp', 'OrderElements')
        Product = apps.get_model('foodcartapp', 'Product')
        for order in OrderElements.objects.all():
            product = Product.objects.get(id=order.product_id)
            order.price = product.price
            order.save()

    operations = [
        migrations.RunPython(update_price_from_product),
    ]
