# Generated by Django 3.2.15 on 2023-08-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230816_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Завершен', 'Завершен'), ('В пути', 'В пути'), ('Готовится', 'Готовится'), ('Принят', 'Принят'), ('Необработанный', 'Необработанный')], db_index=True, default='Необработанный', max_length=50, verbose_name='статус'),
        ),
    ]
