# Generated by Django 3.2.15 on 2023-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230817_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Электронно', 'Электронно'), ('Наличные', 'Наличные'), ('Не указан', 'Не указан')], db_index=True, default='Не указан', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
