# Generated by Django 3.2.15 on 2023-08-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='готовит ресторан'),
        ),
    ]
