# Generated by Django 3.2.15 on 2023-08-21 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_assigned_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelements',
            name='quantity',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество продуктов в заказе'),
        ),
    ]
