# Generated by Django 3.2.15 on 2023-08-21 07:50

import django.core.validators
from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20230821_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworderelements',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[foodcartapp.models.validate_price, django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='neworderelements',
            name='quantity',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество продуктов в заказе'),
        ),
        migrations.AlterUniqueTogether(
            name='neworderelements',
            unique_together={('order', 'product')},
        ),
    ]
