# Generated by Django 3.2.15 on 2023-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230821_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderElements',
        ),
        migrations.RenameModel(
            old_name='NewOrderElements',
            new_name='OrderElements',
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='order',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='order_elements',
                                    to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='product',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='order_elements',
                                    to='foodcartapp.product', verbose_name='товар'),
        ),
        migrations.AlterModelOptions(
            name='orderelements',
            options={'verbose_name': 'элемент заказа', 'verbose_name_plural': 'элементы заказа'},
        ),
    ]
